"use client";

import { useState } from "react";
import { ChatSidebar } from "@/components/custom/ChatSidebar";
import { ChatInterface } from "@/components/custom/ChatInterface";

// Mock data for demonstration
const MOCK_CHATS = [
    {
        id: "1",
        title: "Getting Started",
        lastMessage: "How can I help you today?",
        timestamp: "2h ago",
    },
    {
        id: "2",
        title: "Project Ideas",
        lastMessage: "Here are some suggestions...",
        timestamp: "1d ago",
    },
    {
        id: "3",
        title: "Code Review",
        lastMessage: "Let me review that for you",
        timestamp: "3d ago",
    },
];

const MOCK_MESSAGES = {
    "1": [
        { id: "m1", role: "assistant" as const, content: "Hello! How can I help you today?" },
        { id: "m2", role: "user" as const, content: "Can you help me with my project?" },
        { id: "m3", role: "assistant" as const, content: "Of course! I'd be happy to help. What kind of project are you working on?" },
    ],
    "2": [
        { id: "m4", role: "user" as const, content: "I need some project ideas" },
        { id: "m5", role: "assistant" as const, content: "Here are some suggestions for your next project:\n\n1. A task management app\n2. A personal blog\n3. An e-commerce platform\n4. A chat application\n\nWhich one interests you most?" },
    ],
    "3": [
        { id: "m6", role: "user" as const, content: "Can you review my code?" },
        { id: "m7", role: "assistant" as const, content: "Let me review that for you. Please share the code you'd like me to look at." },
    ],
};

const DashboardPage = () => {
    const [currentChatId, setCurrentChatId] = useState("1");
    const [chatHistory, setChatHistory] = useState(MOCK_CHATS);
    const [messages, setMessages] = useState(MOCK_MESSAGES[currentChatId as keyof typeof MOCK_MESSAGES] || []);
    const [isSidebarOpen, setIsSidebarOpen] = useState(false);
    const [isCollapsed, setIsCollapsed] = useState(false);

    const handleNewChat = () => {
        const newChatId = `${Date.now()}`;
        const newChat = {
            id: newChatId,
            title: "New Chat",
            lastMessage: "Start a conversation...",
            timestamp: "Just now",
        };
        setChatHistory([newChat, ...chatHistory]);
        setCurrentChatId(newChatId);
        setMessages([]);
    };

    const handleChatSelect = (chatId: string) => {
        setCurrentChatId(chatId);
        setMessages(MOCK_MESSAGES[chatId as keyof typeof MOCK_MESSAGES] || []);
    };

    const handleDeleteChat = (chatId: string) => {
        setChatHistory(chatHistory.filter((chat) => chat.id !== chatId));
        if (chatId === currentChatId && chatHistory.length > 0) {
            const nextChat = chatHistory.find((chat) => chat.id !== chatId);
            if (nextChat) {
                setCurrentChatId(nextChat.id);
                setMessages(MOCK_MESSAGES[nextChat.id as keyof typeof MOCK_MESSAGES] || []);
            }
        }
    };

    const toggleSidebar = () => {
        setIsSidebarOpen(!isSidebarOpen);
    };

    const handleSendMessage = (content: string) => {
        const userMessage = {
            id: `msg-${Date.now()}`,
            role: "user" as const,
            content,
        };

        const newMessages = [...messages, userMessage];
        setMessages(newMessages);

        // Simulate AI response
        setTimeout(() => {
            const aiMessage = {
                id: `msg-${Date.now()}-ai`,
                role: "assistant" as const,
                content: "This is a demo response. In a real application, this would be generated by an AI model.",
            };
            setMessages([...newMessages, aiMessage]);

            // Update chat history
            setChatHistory(chatHistory.map(chat =>
                chat.id === currentChatId
                    ? { ...chat, lastMessage: content.slice(0, 50), timestamp: "Just now" }
                    : chat
            ));
        }, 1000);
    };

    return (
        <>
            {/* Header */}

            {/* Main Content Area - Sidebar + Chat */}
            <div className="flex flex-1 w-full overflow-hidden pt-20 relative">
                {/* Mobile Overlay */}
                {isSidebarOpen && (
                    <div
                        className="fixed inset-0 bg-black/50 z-[90] lg:hidden top-20"
                        onClick={toggleSidebar}
                    />
                )}

                {/* Sidebar - Hidden on mobile by default, toggleable */}
                <aside
                    className={`
                        fixed lg:relative top-20 lg:top-0 bottom-0 left-0 z-[80]
                        transform transition-all duration-200 ease-out
                        ${isSidebarOpen ? 'translate-x-0' : '-translate-x-full lg:translate-x-0'}
                    `}
                >
                    <ChatSidebar
                        currentChatId={currentChatId}
                        onChatSelect={(chatId) => {
                            handleChatSelect(chatId);
                            // Close sidebar on mobile after selection
                            if (window.innerWidth < 1024) {
                                setIsSidebarOpen(false);
                            }
                        }}
                        onNewChat={() => {
                            handleNewChat();
                            // Close sidebar on mobile after creating new chat
                            if (window.innerWidth < 1024) {
                                setIsSidebarOpen(false);
                            }
                        }}
                        chatHistory={chatHistory}
                        onDeleteChat={handleDeleteChat}
                        isCollapsed={isCollapsed}
                        onToggleCollapse={() => setIsCollapsed(!isCollapsed)}
                    />
                </aside>

                {/* Main Chat Area - 80% */}
                <div className="flex-1 relative min-w-0">
                    <ChatInterface
                        messages={messages}
                        onSendMessage={handleSendMessage}
                    />
                </div>
            </div>
        </>
    );
};

export default DashboardPage;